services:
  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: container-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-network

  api:
    image: mahdimcheik/bonprof:latest
    container_name: container-api
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      JWT_KEY: ${JWT_KEY}
      API_BACK_URL: ${API_BACK_URL}
      API_FRONT_URL: ${API_FRONT_URL}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      COOKIES_VALIDITY_DAYS: ${COOKIES_VALIDITY_DAYS}
      TOKEN_VALIDITY_MINUTES: ${TOKEN_VALIDITY_MINUTES}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_KEY: ${SMTP_KEY}
      SMTP_PORT: ${SMTP_PORT}
      DO_NO_REPLY_MAIL: ${DO_NO_REPLY_MAIL}
      MINIO_BUCKETNAME: ${MINIO_BUCKETNAME}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESSKEY: ${MINIO_ACCESSKEY}
      MINIO_SECRETKEY: ${MINIO_SECRETKEY}
      FILER_URL: ${FILER_URL}

    expose:
      - 7113
    networks:
      - local-network
      - global-network
    volumes:
      - images:/app/wwwroot/images
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  local-network:
    driver: bridge
  global-network:
    external: true